### ISSUE TITLE
halaman ajukan topik

### ISSUE THREAD

**Issue by iamyuu** [svelteid/website#4]
sebagai contoh bisa lihat [react id](https://reactjs.id/submit-a-talk)

**Comment by alfinsyahruddin** [comment]
ini sepertinya belum ada yang ngerjain, aku mau ngerjain yang ini boleh mas @iamyuu ? 😁

**Comment by iamyuu** [comment]
Silahkan mas @al-fin, oh iya halaman ini kalo bisa pake mdsvex ya biar gampang rubahnya
