### ISSUE TITLE
halaman kode

### ISSUE THREAD

**Issue by iamyuu** [svelteid/website#6]
halaman ini akan berisi boilerplate, plugin, dan hal-hal lain yang berhubungan dengan kode

**Comment by alfinsyahruddin** [comment]
aku mau ngerjain yang ini ya mas @iamyuu 😁

**Comment by iamyuu** [comment]
cool, halaman idenya adalah bakal berisi kaya [svelte-community/code](https://svelte-community.netlify.app/code). Desainnya ga ada, silahkan berimajinasi.

**Comment by alfinsyahruddin** [comment]
siap mas @iamyuu , udah aku PR
https://github.com/svelteid/website/pull/15
